---
title: "Conversion bewteen RDD and DataFrame"
author: "Ming Chen"
date: "6/17/2017"
output: 
  html_document:
    number_sections: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
---

<style>
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```


## Create SparkContext & SparkSession

**SparkContext**

```{python}
from pyspark import SparkContext
sc = SparkContext(master = 'local')
```

**SparkSession**

```{python}
from pyspark.sql import SparkSession
spark = SparkSession.builder \
          .appName("Learning Apach Spark") \
          .config("spark.some.config.option", "some-value") \
          .getOrCreate()
```


## Example DataFrame

```{python}
mtcars = spark.read.csv(path='data/mtcars.csv',
                        sep=',',
                        encoding='UTF-8',
                        comment=None,
                        header=True, 
                        inferSchema=True)
```


## DataFrame to RDD

A **DataFrame** can be easily converted to an **RDD** by calling the `pyspark.sql.DataFrame.rdd()` function.

```{python}
mtcars.rdd.take(2)
```

Each element in the returned RDD is an **pyspark.sql.Row** object. An *Row* is a list of key-value pairs.
```
[Row(_c0='Mazda RX4', mpg=21.0, cyl=6, disp=160.0, hp=110, drat=3.9, wt=2.62, qsec=16.46, vs=0, am=1, gear=4, carb=4),
 Row(_c0='Mazda RX4 Wag', mpg=21.0, cyl=6, disp=160.0, hp=110, drat=3.9, wt=2.875, qsec=17.02, vs=0, am=1, gear=4, carb=4)]
```

With an RDD object, we can apply a set of mapping functions, such as `map`, `mapValues`, `flatMap`, `flatMapValues` and a lot of other methods that come from RDD.

```{python}
mtcars_map = mtcars.rdd.map(lambda x: (x['_c0'], x['mpg']))
mtcars_map.take(5)
```

```
[('Mazda RX4', 21.0),
 ('Mazda RX4 Wag', 21.0),
 ('Datsun 710', 22.8),
 ('Hornet 4 Drive', 21.4),
 ('Hornet Sportabout', 18.7)]
```

```{python}
mtcars_mapvalues = mtcars_map.mapValues(lambda x: [x, x * 10])
mtcars_mapvalues.take(5)
```

```
[('Mazda RX4', [21.0, 210.0]),
 ('Mazda RX4 Wag', [21.0, 210.0]),
 ('Datsun 710', [22.8, 228.0]),
 ('Hornet 4 Drive', [21.4, 214.0]),
 ('Hornet Sportabout', [18.7, 187.0])]
```

## RDD to DataFrame

To convert an **RDD** to a **DataFrame**, we can use the `SparkSession.createDataFrame()` function. Every element in the RDD has be to an **Row**.

**Create an RDD**

```{python}
rdd_raw = sc.textFile('data/mtcars.csv')
rdd_raw.take(5)
```

```
[',mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb',
 'Mazda RX4,21,6,160,110,3.9,2.62,16.46,0,1,4,4',
 'Mazda RX4 Wag,21,6,160,110,3.9,2.875,17.02,0,1,4,4',
 'Datsun 710,22.8,4,108,93,3.85,2.32,18.61,1,1,4,1',
 'Hornet 4 Drive,21.4,6,258,110,3.08,3.215,19.44,1,0,3,1']
```

**Save the first row to a variable**

```{python}
header = rdd_raw.map(lambda x: x.split(',')).filter(lambda x: x[1] == 'mpg').collect()[0]
header[0] = 'model'
header
```

```
['model',
 'mpg',
 'cyl',
 'disp',
 'hp',
 'drat',
 'wt',
 'qsec',
 'vs',
 'am',
 'gear',
 'carb']
```

**Save the rest to a new RDD**

```{python}
rdd = rdd_raw.map(lambda x: x.split(',')).filter(lambda x: x[1] != 'mpg')
rdd.take(2)
```

```
[['Mazda RX4',
  '21',
  '6',
  '160',
  '110',
  '3.9',
  '2.62',
  '16.46',
  '0',
  '1',
  '4',
  '4'],
 ['Mazda RX4 Wag',
  '21',
  '6',
  '160',
  '110',
  '3.9',
  '2.875',
  '17.02',
  '0',
  '1',
  '4',
  '4']]
```

**Convert RDD elements to RDD `Row` objects**

First we define a function which takes a list of column names and a list of values and create a `Row` of key-value pairs. **Since keys in an Row object are variable names, we can't simply pass a dictionary to the `Row()` function**. We can think of a dictionary as an argument list and use the `**` to unpack the argument list.

See an example.

```{python}
my_dict = dict(zip(['a', 'b', 'c'], range(1:4)))
Row(**my_dict)
```

An **Row** is very like a function call expression.

```
Row(a=1, b=2, c=3)
```

Let's define the function.

```{python}
def list_to_row(keys, values):
    row_dict = dict(zip(keys, values))
    return Row(**row_dict)
```

**Convert elements to RDD objects**

```{python}
rdd_rows = rdd.map(lambda x: list_to_row(header, x))
rdd_rows.take(3)
```

```
[Row(am='1', carb='4', cyl='6', disp='160', drat='3.9', gear='4', hp='110', model='Mazda RX4', mpg='21', qsec='16.46', vs='0', wt='2.62'),
 Row(am='1', carb='4', cyl='6', disp='160', drat='3.9', gear='4', hp='110', model='Mazda RX4 Wag', mpg='21', qsec='17.02', vs='0', wt='2.875'),
 Row(am='1', carb='1', cyl='4', disp='108', drat='3.85', gear='4', hp='93', model='Datsun 710', mpg='22.8', qsec='18.61', vs='1', wt='2.32')]
```

Now we can convert the RDD to a DataFrame.

```{python}
df = spark.createDataFrame(rdd_rows)
df.show(5)
```

```
+---+----+---+----+----+----+---+-----------------+----+-----+---+-----+
| am|carb|cyl|disp|drat|gear| hp|            model| mpg| qsec| vs|   wt|
+---+----+---+----+----+----+---+-----------------+----+-----+---+-----+
|  1|   4|  6| 160| 3.9|   4|110|        Mazda RX4|  21|16.46|  0| 2.62|
|  1|   4|  6| 160| 3.9|   4|110|    Mazda RX4 Wag|  21|17.02|  0|2.875|
|  1|   1|  4| 108|3.85|   4| 93|       Datsun 710|22.8|18.61|  1| 2.32|
|  0|   1|  6| 258|3.08|   3|110|   Hornet 4 Drive|21.4|19.44|  1|3.215|
|  0|   2|  8| 360|3.15|   3|175|Hornet Sportabout|18.7|17.02|  0| 3.44|
+---+----+---+----+----+----+---+-----------------+----+-----+---+-----+
```

## Merge and split columns

Sometimes we need to merge multiple columns in a Dataframe into one column, or split a column into multiple columns. We can easily achieve this by converting a DataFrame to RDD, applying map functions to manipulate elements, and then converting the RDD back to a DataFrame.

**Convert DataFrame to RDD and merge values**

```{python}
rdd_merged = df.rdd.map(lambda x: Row(model=x[7], values=list(map(float, x[:7] + x[8:]))))
rdd_merged.take(4)
```

```
[Row(model='Mazda RX4', values=[1.0, 4.0, 6.0, 160.0, 3.9, 4.0, 110.0, 21.0, 16.46, 0.0, 2.62]),
 Row(model='Mazda RX4 Wag', values=[1.0, 4.0, 6.0, 160.0, 3.9, 4.0, 110.0, 21.0, 17.02, 0.0, 2.875]),
 Row(model='Datsun 710', values=[1.0, 1.0, 4.0, 108.0, 3.85, 4.0, 93.0, 22.8, 18.61, 1.0, 2.32]),
 Row(model='Hornet 4 Drive', values=[0.0, 1.0, 6.0, 258.0, 3.08, 3.0, 110.0, 21.4, 19.44, 1.0, 3.215])]
```

**Convert RDD back to DataFrame**

```{python}
df_merged = spark.createDataFrame(rdd_merged)
df_merged.show(5, truncate=False)
```

```
+-----------------+-----------------------------------------------------------------+
|model            |values                                                           |
+-----------------+-----------------------------------------------------------------+
|Mazda RX4        |[1.0, 4.0, 6.0, 160.0, 3.9, 4.0, 110.0, 21.0, 16.46, 0.0, 2.62]  |
|Mazda RX4 Wag    |[1.0, 4.0, 6.0, 160.0, 3.9, 4.0, 110.0, 21.0, 17.02, 0.0, 2.875] |
|Datsun 710       |[1.0, 1.0, 4.0, 108.0, 3.85, 4.0, 93.0, 22.8, 18.61, 1.0, 2.32]  |
|Hornet 4 Drive   |[0.0, 1.0, 6.0, 258.0, 3.08, 3.0, 110.0, 21.4, 19.44, 1.0, 3.215]|
|Hornet Sportabout|[0.0, 2.0, 8.0, 360.0, 3.15, 3.0, 175.0, 18.7, 17.02, 0.0, 3.44] |
+-----------------+-----------------------------------------------------------------+
only showing top 5 rows
```

**Split the *values* column to two columns**

```{python}
df_3_columns = df_merged.rdd.map(lambda x: Row(model=x[0], x1=x[1][:4], x2=x[1][4:]))
df_3_columns.take(5)
```

```
[Row(model='Mazda RX4', x1=[1.0, 4.0, 6.0, 160.0], x2=[3.9, 4.0, 110.0, 21.0, 16.46, 0.0, 2.62]),
 Row(model='Mazda RX4 Wag', x1=[1.0, 4.0, 6.0, 160.0], x2=[3.9, 4.0, 110.0, 21.0, 17.02, 0.0, 2.875]),
 Row(model='Datsun 710', x1=[1.0, 1.0, 4.0, 108.0], x2=[3.85, 4.0, 93.0, 22.8, 18.61, 1.0, 2.32]),
 Row(model='Hornet 4 Drive', x1=[0.0, 1.0, 6.0, 258.0], x2=[3.08, 3.0, 110.0, 21.4, 19.44, 1.0, 3.215]),
 Row(model='Hornet Sportabout', x1=[0.0, 2.0, 8.0, 360.0], x2=[3.15, 3.0, 175.0, 18.7, 17.02, 0.0, 3.44])]
```

```{python}
spark.createDataFrame(df_3_columns).show(5, truncate=False)
```

```
+-----------------+----------------------+-------------------------------------------+
|model            |x1                    |x2                                         |
+-----------------+----------------------+-------------------------------------------+
|Mazda RX4        |[1.0, 4.0, 6.0, 160.0]|[3.9, 4.0, 110.0, 21.0, 16.46, 0.0, 2.62]  |
|Mazda RX4 Wag    |[1.0, 4.0, 6.0, 160.0]|[3.9, 4.0, 110.0, 21.0, 17.02, 0.0, 2.875] |
|Datsun 710       |[1.0, 1.0, 4.0, 108.0]|[3.85, 4.0, 93.0, 22.8, 18.61, 1.0, 2.32]  |
|Hornet 4 Drive   |[0.0, 1.0, 6.0, 258.0]|[3.08, 3.0, 110.0, 21.4, 19.44, 1.0, 3.215]|
|Hornet Sportabout|[0.0, 2.0, 8.0, 360.0]|[3.15, 3.0, 175.0, 18.7, 17.02, 0.0, 3.44] |
+-----------------+----------------------+-------------------------------------------+
only showing top 5 rows
```


