---
title: "StringIndexer and VectorIndexer"
author: "Wenqiang Feng & Ming Chen"
date: "2/19/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## **StringIndexer** and **VectorIndexer**

* **StringIndexer** 
    + converts a single column to an *index column* (similar to a factor column in R)
* **VectorIndexer** 
    + is used to index categorical predictors in a **featuresCol** column. Remember that **featuresCol** is a single column consisting of vectors (refer to [featuresCol and labelCol](featuresCol-and-labelCol.html)). Each row is a vector which contains values from each predictors.
    + if you have string type predictors, you will first need to use index those columns with **StringIndexer**. **featuresCol** contains vectors, and vectors does not contain string values.
    
## Example

Data resource: [http://www.ats.ucla.edu/stat/r/modules/dummy_vars.htm](http://www.ats.ucla.edu/stat/r/modules/dummy_vars.htm). I modified that *female* column and generate a new dataset called *hsb2_modified.csv*.

## Set up sparkContext and sparkSession

```{python}
# connecting to spark
from pyspark import SparkConf, SparkContext
## set up spark context
conf = SparkConf().setAppName("myApp")
sc = SparkContext(conf=conf)

# create sparksession object
from pyspark.sql import SparkSession
sparksession = SparkSession(sc)
```

## Import data
```{python}
hsb2 = sparksession.read.csv("data/hsb2_modified.csv", inferSchema=True, header=True)
hsb2.show(n=5)
```

```{python}
+---+------+----+---+------+----+----+-----+----+-------+-----+
| id|gender|race|ses|schtyp|prog|read|write|math|science|socst|
+---+------+----+---+------+----+----+-----+----+-------+-----+
| 70|  male|   4|  1|     1|   1|  57|   52|  41|     47|   57|
|121|female|   4|  2|     1|   3|  68|   59|  53|     63|   61|
| 86|  male|   4|  3|     1|   1|  44|   33|  54|     58|   31|
|141|  male|   4|  3|     1|   3|  63|   44|  47|     53|   56|
|172|  male|   4|  2|     1|   2|  47|   52|  57|     53|   61|
+---+------+----+---+------+----+----+-----+----+-------+-----+
```

## Use `StringIndexer` to index string column

```{python}
from pyspark.ml.feature import StringIndexer
indexer = StringIndexer(inputCol='gender', outputCol='indexed_gender')
model = indexer.fit(hsb2)
hsb2 = model.transform(hsb2)
hsb2.show(n=5)
```

```{python}
## see indexed_gender column
+---+------+----+---+------+----+----+-----+----+-------+-----+--------------+
| id|gender|race|ses|schtyp|prog|read|write|math|science|socst|indexed_gender|
+---+------+----+---+------+----+----+-----+----+-------+-----+--------------+
| 70|  male|   4|  1|     1|   1|  57|   52|  41|     47|   57|           1.0|
|121|female|   4|  2|     1|   3|  68|   59|  53|     63|   61|           0.0|
| 86|  male|   4|  3|     1|   1|  44|   33|  54|     58|   31|           1.0|
|141|  male|   4|  3|     1|   3|  63|   44|  47|     53|   56|           1.0|
|172|  male|   4|  2|     1|   2|  47|   52|  57|     53|   61|           1.0|
+---+------+----+---+------+----+----+-----+----+-------+-----+--------------+
```

## Transform data into `featuresCol` and `labelCol` structure

```{python}
from pyspark.ml.linalg import Vectors
from pyspark.sql import Row
new_hsb2 = hsb2.rdd.map(lambda row: Row(label=row['socst'],
                                        features=Vectors.dense([
                                            row['indexed_gender'],
                                            row['race'],
                                            row['ses'],
                                            row['schtyp'],
                                            row['prog'],
                                            row['read'],
                                            row['write'],
                                            row['math'],
                                            row['science']])
                                        )).toDF()
new_hsb2.show(n=5)
```

```{python}
+--------------------+-----+
|            features|label|
+--------------------+-----+
|[1.0,4.0,1.0,1.0,...|   57|
|[0.0,4.0,2.0,1.0,...|   61|
|[1.0,4.0,3.0,1.0,...|   31|
|[1.0,4.0,3.0,1.0,...|   56|
|[1.0,4.0,2.0,1.0,...|   61|
+--------------------+-----+
```


## Use `VectorIndexer` to index categorical predictors in `featuresCol`

```{python}
from pyspark.ml.feature import VectorIndexer
indexer = VectorIndexer(maxCategories=4, inputCol='features', outputCol='indexed_features')
model = indexer.fit(new_hsb2)
indexed_new_hsb2 = model.transform(new_hsb2)
indexed_new_hsb2.take(2)
```

```{python}
# before indexing featuresCol  # after indexing featuresCol
+--------------------+-----+  +--------------------+-----+--------------------+
|            features|label|  |            features|label|    indexed_features|
+--------------------+-----+  +--------------------+-----+--------------------+
|[1.0,4.0,1.0,1.0,...|   57|  |[1.0,4.0,1.0,1.0,...|   57|[1.0,3.0,0.0,0.0,...|
|[0.0,4.0,2.0,1.0,...|   61|  |[0.0,4.0,2.0,1.0,...|   61|[0.0,3.0,1.0,0.0,...|
|[1.0,4.0,3.0,1.0,...|   31|  |[1.0,4.0,3.0,1.0,...|   31|[1.0,3.0,2.0,0.0,...|
|[1.0,4.0,3.0,1.0,...|   56|  |[1.0,4.0,3.0,1.0,...|   56|[1.0,3.0,2.0,0.0,...|
|[1.0,4.0,2.0,1.0,...|   61|  |[1.0,4.0,2.0,1.0,...|   61|[1.0,3.0,1.0,0.0,...|
+--------------------+-----+  +--------------------+-----+--------------------+
```


* **Fitting a linear model**

```{python}
from pyspark.ml.regression import LinearRegression
lr = LinearRegression(featuresCol='indexed_features', labelCol='label')
model = lr.fit(indexed_new_hsb2)
model.transform(indexed_new_hsb2).show()
```

```{python}
+--------------------+-----+--------------------+------------------+
|            features|label|    indexed_features|        prediction|
+--------------------+-----+--------------------+------------------+
|[1.0,4.0,1.0,1.0,...|   57|[1.0,3.0,0.0,0.0,...| 51.80048015803359|
|[0.0,4.0,2.0,1.0,...|   61|[0.0,3.0,1.0,0.0,...|58.243471181988404|
|[1.0,4.0,3.0,1.0,...|   31|[1.0,3.0,2.0,0.0,...| 45.60938102700539|
|[1.0,4.0,3.0,1.0,...|   56|[1.0,3.0,2.0,0.0,...| 53.16002885219301|
|[1.0,4.0,2.0,1.0,...|   61|[1.0,3.0,1.0,0.0,...| 50.59419095464209|
|[1.0,4.0,2.0,1.0,...|   61|[1.0,3.0,1.0,0.0,...|48.200748866519014|
|[1.0,3.0,2.0,1.0,...|   61|[1.0,2.0,1.0,0.0,...| 53.93023551618455|
|[1.0,1.0,2.0,1.0,...|   36|[1.0,0.0,1.0,0.0,...|43.258280997139416|
|[1.0,4.0,2.0,1.0,...|   51|[1.0,3.0,1.0,0.0,...| 58.89692949834014|
|[1.0,3.0,2.0,1.0,...|   51|[1.0,2.0,1.0,0.0,...|  54.8926363226898|
|[1.0,4.0,2.0,1.0,...|   61|[1.0,3.0,1.0,0.0,...|   50.950400342767|
|[1.0,4.0,2.0,1.0,...|   61|[1.0,3.0,1.0,0.0,...|  57.6279630554164|
|[1.0,4.0,3.0,1.0,...|   71|[1.0,3.0,2.0,0.0,...| 66.25089147947871|
|[1.0,4.0,3.0,1.0,...|   46|[1.0,3.0,2.0,0.0,...|59.341701186507144|
|[1.0,3.0,1.0,1.0,...|   56|[1.0,2.0,0.0,0.0,...| 49.98714372879461|
|[1.0,4.0,1.0,1.0,...|   56|[1.0,3.0,0.0,0.0,...|45.370862024502635|
|[1.0,4.0,3.0,1.0,...|   56|[1.0,3.0,2.0,0.0,...| 52.42836867774257|
|[1.0,4.0,2.0,2.0,...|   56|[1.0,3.0,1.0,1.0,...| 57.14432439272428|
|[1.0,4.0,3.0,1.0,...|   61|[1.0,3.0,2.0,0.0,...|  65.6544475938724|
|[1.0,4.0,2.0,1.0,...|   46|[1.0,3.0,1.0,0.0,...|50.080534041206725|
+--------------------+-----+--------------------+------------------+
```

