---
title: "Pyspark Vectors"
author: "Wenqiang Feng & Ming Chen"
date: "2/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Remark:

- You can download the complete [ipython notebook](./ipynb/vector.ipynb) for the this session.


## Dense vector vs. Sparse vector

* Both dense vector and sparse vector are homogeneous and can only have numeric data.

* `DenseVector` takes one single argument and is very like an R vector.
* `SparseVector` only display non-zero values. `SparseVector` uses three values to achieve this. The non-value entries' indices (positions) and corresponding values, and the vector size. With this information, you can figure out which entries in a vector have zero values, and therefore, a complete vector.

## Example:

  + set up spark context and  SparkSession

```{python eval =FALSE}
from pyspark import SparkConf, SparkContext
## set up spark context
from pyspark.sql import SQLContext
sc = SparkContext()
sqlContext = SQLContext(sc)
## set up  SparkSession
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()
```

  + import `Vectors` from pyspark library
  
```{python eval=FALSE}
from pyspark.ml.linalg import Vectors
```  

  + dense vector
  
```{python eval=FALSE}
densevector = Vectors.dense([1,3,4,2.5])
densevector
```

```{python eval=FALSE}
# output
DenseVector([1.0, 3.0, 4.0, 2.5])
```

```{python eval=FALSE}
densevector.toArray()
```

```{python eval=FALSE}
# output
array([ 1. ,  3. ,  4. ,  2.5])
```
  + sparse vector
    = The sparse vector below is a representation of vector [ 0. ,  3. ,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]
    
```{python eval=FALSE}
sparseVector = Vectors.sparse(10, [1, 3], [3.0, 4.5])
sparseVector.toArray()
```

```{python eval=FALSE}
# output
array([ 0. ,  3. ,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ])
```